# vcl/parser.py
import re
from typing import List

def transpile_vcl_to_python(source: str, mode: str = "dev") -> str:
    lines = source.splitlines()
    output: List[str] = []
    in_vibe_block = False
    persist_vars = {}  # name -> type/default

    for line in lines:
        stripped = line.strip()

        # Skip empty lines
        if not stripped:
            output.append(line)
            continue

        # vibe block handling
        if stripped.startswith("vibe ") and "{" in stripped:
            in_vibe_block = True
            if mode == "prod":
                continue  # skip whole block in prod
            else:
                output.append(f"# {line}")  # comment it out in dev
                continue

        if in_vibe_block:
            if "}" in stripped:
                in_vibe_block = False
            if mode == "prod":
                continue
            else:
                output.append(f"# {line}")
            continue

        # persist handling
        persist_match = re.match(r'persist\s+(\w+):\s*(\w+)\s*=\s*(.+)', stripped)
        if persist_match:
            name, typ, default = persist_match.groups()
            persist_vars[name] = (typ, default.strip())

            if mode == "prod":
                # Replace with actual persist logic
                output.append(f"# Persisted var: {name}")
                output.append(f"try:\n    with open('{name}.pkl', 'rb') as f:\n        {name} = pickle.load(f)\nexcept:\n    {name} = {default}")
                output.append(f"def save_{name}():\n    with open('{name}.pkl', 'wb') as f:\n        pickle.dump({name}, f)")
            else:
                output.append(f"# persist {name}: {typ} = {default}  # will be persisted")
                output.append(f"{name} = {default}")
            continue

        # Default: pass through (future: more transforms)
        output.append(line)

    # Add imports we need
    header = [
        "import pickle",
        "import random",  # from our example
        "# Auto-generated by VCL transpiler\n"
    ]

    return "\n".join(header + output)
